name: Tests

on:
  push:
    branches:
      - master

jobs:
  build-test-migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.300

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
